from numpy import ndarray
from typing import Union, Iterable, Any, Optional

def tile(A: Union[ndarray, Iterable, int, float],
         reps: Union[ndarray, Iterable, int, float]) -> Any: ...

def column_stack(tup: Any) -> Any:...

def vstack(tup: Iterable) -> Any:...

def hstack(tup: Iterable) -> Any:...

def atleast_2d(*arys: Any) -> list:...
